#!/bin/bash
# Script para automatizar a configuração inicial do WordPress

set -e

echo "📥 Baixando arquivos do WordPress..."
ddev wp core download --force

echo "🛠️  Instalando WordPress..."
ddev wp core install --url="https://smart-gallery-filter.ddev.site" --title="Smart Gallery Filter" --admin_user="admin" --admin_password="admin" --admin_email="admin@local.test"

echo "🔌 Ativando plugins smart-gallery-filter"
ddev wp plugin activate smart-gallery-filter

echo "🔌🗑️  Desinstalando plugins: akismet, hello-plus..."
ddev wp plugin uninstall akismet hello-plus

echo "🔌📥 Instalando e ativando plugins: elementor, pods"
ddev wp plugin install elementor pods --activate

echo "🎨📥 Instalando e ativando tema hello-biz"
ddev wp theme install hello-biz --activate

ddev describe
